#!/bin/bash
# WF 2025-05-25
# Muda-freier SPARQL query wrapper with argument loop

cd genwiki_examples || exit 2

args=(-en qlever-wikidata --prefixes -qp queries.yaml)

added=0
for arg in "$@"; do
  case "$arg" in
    -*) break ;;  # alle Optionen (auch -h, -f, --list)
    *)
      if (( added == 0 )); then
        args+=(-qn "$arg")
      elif (( added == 1 )); then
        args+=(--params "$arg")
      fi
      added=$((added + 1))
      shift
      ;;
  esac
done

args+=("$@")
sparqlquery "${args[@]}"
